[0m15:28:24.433688 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC13C0340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC360BBE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC360BDF0>]}


============================== 15:28:24.438029 | 9edefc16-443c-4458-91c0-5f600ed15209 ==============================
[0m15:28:24.438029 [info ] [MainThread]: Running with dbt=1.10.6
[0m15:28:24.439031 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init sofia_health', 'send_anonymous_usage_stats': 'True'}
[0m15:28:24.461068 [debug] [MainThread]: Starter project path: C:\Users\marco\Desktop\desafio_sofia\venv\lib\site-packages\dbt\include\starter_project
[0m15:28:24.529843 [info ] [MainThread]: 
Your new dbt project "sofia_health" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:28:24.529843 [info ] [MainThread]: Setting up your profile.
[0m15:30:49.195117 [info ] [MainThread]: Profile sofia_health written to C:\Users\marco\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:30:49.198117 [debug] [MainThread]: Command `dbt init` succeeded at 15:30:49.197117 after 144.85 seconds
[0m15:30:49.199114 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC13C0340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC360BF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012BC2D88610>]}
[0m15:30:49.200106 [debug] [MainThread]: Flushing usage events
[0m15:30:50.092550 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:38:10.761657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B47F0370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B5A5E860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B5A5EA40>]}


============================== 11:38:10.766352 | 6e3b05e0-3582-4ac5-b1ab-470d653b9d24 ==============================
[0m11:38:10.766352 [info ] [MainThread]: Running with dbt=1.10.6
[0m11:38:10.767383 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_providers', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:38:10.767383 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\Desktop\desafio_sofia\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:38:10.768631 [debug] [MainThread]: Command `dbt run` failed at 11:38:10.768631 after 0.09 seconds
[0m11:38:10.770133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B47F0370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B5A5E770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B5A5E7A0>]}
[0m11:38:10.770133 [debug] [MainThread]: Flushing usage events
[0m11:38:12.211920 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:47:48.907264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026679540370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667B78E860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667B78EA40>]}


============================== 11:47:48.911263 | bd58a641-a1c9-4bc3-93c4-402e8d066af1 ==============================
[0m11:47:48.911263 [info ] [MainThread]: Running with dbt=1.10.6
[0m11:47:48.911263 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_claims', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:47:48.912716 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\Desktop\desafio_sofia\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:47:48.913893 [debug] [MainThread]: Command `dbt run` failed at 11:47:48.913893 after 0.09 seconds
[0m11:47:48.915074 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026679540370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667B78E770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667B78E7A0>]}
[0m11:47:48.915074 [debug] [MainThread]: Flushing usage events
[0m11:47:49.723652 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:48:02.510833 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6BFC0370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6E20E860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6E20EA40>]}


============================== 11:48:02.514841 | 882a327b-354d-4028-83a6-10630f2b933c ==============================
[0m11:48:02.514841 [info ] [MainThread]: Running with dbt=1.10.6
[0m11:48:02.514841 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select stg_claims', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:48:02.516171 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\Desktop\desafio_sofia\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:48:02.517169 [debug] [MainThread]: Command `dbt run` failed at 11:48:02.517169 after 0.09 seconds
[0m11:48:02.518168 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6BFC0370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6E20E770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6E20E7A0>]}
[0m11:48:02.518168 [debug] [MainThread]: Flushing usage events
[0m11:48:03.263012 [debug] [MainThread]: An error was encountered while trying to flush usage events
